version: 0.2

phases:
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/kinesis-video-native-build
      - pwd
      - apt-get install gcc-arm-linux-gnueabihf
      - ls
      - ./install-script -a
      - ./gstreamer-plugin-install-script
    finally:
      - echo This always runs even if the install command fails
artifacts:
  files:
    - $CODEBUILD_SRC_DIR/kinesis-video-native-build/downloads/local/lib/**/*
    - $CODEBUILD_SRC_DIR/kinesis-video-native-build/downloads/local/include/**/*
    - $CODEBUILD_SRC_DIR/kinesis-video-native-build/libproducer.so
    - $CODEBUILD_SRC_DIR/kinesis-video-gstreamer-plugin/libgstkvssink.so
  discard-paths: no
